### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ajitesh13**
i have updated README.md, please check it and let me know if anything is wrong

### CODE REVIEW

**Comment by chriswmackey** [comment]
Sorry that I was late in responding. @mostaphaRoudsari originally mispoke on the original issue. We don't need anything like the honeybee repo but something more like the [honeybee-core repo](https://github.com/ladybug-tools/honeybee-core)

**Comment by chriswmackey** [comment]
Let me know if you still want to tackle this, @Ajitesh13 , (now that you know what template you should follow) or of it's better to just close the issue.

**Comment by Ajitesh13** [comment]
Yeah, i want to fix this.

**Comment by chriswmackey** [comment]
Sorry @Ajitesh13 ,
This has already been addressed in another PR: https://github.com/ladybug-tools/honeybee-energy/pull/43

**Pull request closed without merging**
