### PR TITLE
feat(properties) add properties that can be extended

### PR DESCRIPTION
**Pull request by PH-Tools**
Following the same pattern from #823 ,  adding a new **.properties** to HB-E [hvac.IdealAirSystem](https://github.com/ladybug-tools/honeybee-energy/blob/4cfb86c040a4587d8bb48715db37749040e82d4c/honeybee_energy/hvac/idealair.py#L15) class in order to allow for extension by plugins.

All hvac tests pass
Note: for consistency, I can add .properties to the rest of the hvac classes if you would like? (allair, doas, heatcool)

### CODE REVIEW

**Review by chriswmackey — CHANGES_REQUESTED** [review]
Hey @PH-Tools ,

This generally looks good and thanks for adding this. There's just one change that you need to make and then we can merge.

**Comment by PH-Tools** [comment]
Hi @chriswmackey 
Not a problem - that all makes sense. I have updated my commits to reflect those changes - hopefully that all worked properly now?

thanks!

**Review by chriswmackey — APPROVED** [review]
LGTM! Let's merge!

**Comment by PH-Tools** [comment]
awesome! Thanks!!

**Pull request merged**
