### PR TITLE
build(docker): set up docker container to run energy simulations using honeybee-energy

### PR DESCRIPTION
**Pull request by AntoineDao**
Note that the dockerfile hard codes the depdency versions (openstudio and honeybee-openstudio-gem). The image size for this implementation is roughly 550 MB.

#253

### CODE REVIEW

**Comment by AntoineDao** [comment]
@chriswmackey I think I'm 90% there. I tried to run a simulation and get a fun/super opaque energyplus error:

```console
> honeybee-energy simulate model /home/ladybugbot/run/model.json /home/ladybugbot/run/weather.epw --folder

/home/ladybugbot/run/simulation --log-file sim.log
honeybee.cli.validate - ERROR - honeybee_schema is not installed. Try `pip install . [cli]` command.
Traceback (most recent call last):
  File "/home/ladybugbot/.local/lib/python3.7/site-packages/honeybee/cli/validate.py", line 20, in <module>
    import honeybee_schema.model as schema_model
ModuleNotFoundError: No module named 'honeybee_schema'
Starting Model translation from Honeybee to OpenStudio
Translating Materials
Translating Constructions
Translating ConstructionSets
Translating Schedules
Translating ProgramTypes
Translating Default ConstructionSet
Translating Room Geometry
Translating HVAC Systems
Translating Context Shade Geometry
Done with Model translation!
Copying Energy+.idd to /home/ladybugbot/run/simulation/run
Copying weather.epw to /home/ladybugbot/run/simulation/run
ExpandObjects Started.
No expanded file generated.
ExpandObjects Finished. Time:     0.015
EnergyPlus Starting
EnergyPlus, Version 9.3.0-baff08990c, YMD=2020.07.01 13:04
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
/home/ladybugbot/run/simulation/run/in.sh: line 6:    14 Segmentation fault      (core dumped) /home/ladybugbot/ladybug_tools/openstudio/EnergyPlus/energyplus
```

You should be able to reproduce the error:
1. Be in the "honeybee-energy" repository in a terminal
2. Create empty "simulation" folder (this is where all the output files will be dumped)
3. Build the docker container: `docker build . -t test`
4. Run the container (this command should work if you use a unix shell inside your windows machine to run it, such as the git shell):
```console
> docker run --rm -it \
    -v $(pwd)/simulation:/home/ladybugbot/run/simulation \
    -v $(pwd)/tests/json/ShoeBox.json:/home/ladybugbot/run/model.json \
    -v $(pwd)/tests/simulation/chicago.epw:/home/ladybugbot/run/weather.epw \
    test \
    honeybee-energy simulate model /home/ladybugbot/run/model.json /home/ladybugbot/run/weather.epw --folder /home/ladybugbot/run/simulation --log-file sim.log
```

It's possible the issue is with my inputs rathter than the container. I am trying to run a simulation using the model in `testts/json/ShoeBox.json` and the weather file at `tests/simulation/chicago.epw`. Are they maybe expected to fail a simulation when used as inputs?

**Comment by chriswmackey** [comment]
@AntoineDao ,
I have never encountered that EnergyPlus error before and I really don't know what it means. [I'm reading the Wikipedia page on Segmentation Fault](https://en.wikipedia.org/wiki/Segmentation_fault) to try and understand what is happening but it's definitely specific to this docker image (and maybe it's memory protection?) and not some broader issue with EnergyPlus or honeybee.

The `tests/json/ShoeBox.json` and the weather file at `tests/simulation/chicago.epw` produce a correct simulation outside of the docker image.

**Comment by mostaphaRoudsari** [comment]
I would also try to run it as a root user first before testing it with a user account and see if that makes a difference. ¯\_(ツ)_/¯

**Comment by AntoineDao** [comment]
I have done a few more runs and am still at a loss...

* **root**: I have tried running it on my local machine as root and non-root and get the same result. 
* **EnergyPlus 9.2.0**: I tried a previous version of energyplus in case it was a freak bug. I got a different more detailed error message. Not sure if it's related to the issue with EnergyPlus 9.3.0.

```console
Program Version,EnergyPlus, Version 9.2.0-921312fa1d, YMD=2020.07.02 15:52,
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][calculation_frequency] - Value type "string" for input "Periodic" not permitted by 'type' constraint.
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][calculation_method] - "PolygonClipping" - Failed to match against any enum values.
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][external_shading_calculation_method] - "512" - Failed to match against any enum values.
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][maximum_figures_in_shadow_overlap_calculations] - "30" - Expected number greater than or equal to 200.000000
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][output_external_shading_calculation_results] - "SimpleSkyDiffuseModeling" - Failed to match against any enum values.
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][polygon_clipping_algorithm] - "15000" - Failed to match against any enum values.
   ** Severe  ** <root>[ShadowCalculation][ShadowCalculation 1][sky_diffuse_modeling_algorithm] - "SutherlandHodgman" - Failed to match against any enum values.
   ** Warning ** Version: in IDF="9.3" not the same as expected="9.2"
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=7
   ..... Last severe error=<root>[ShadowCalculation][ShadowCalculation 1][sky_diffuse_modeling_algorithm] - "SutherlandHodgman" - Failed to match against any enum values.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 1 Warning; 7 Severe Errors; Elapsed Time=00hr 00min  0.18sec
``` 

Here is the folder generated by Honeybee-Energy: [simulation.zip](https://github.com/ladybug-tools/honeybee-energy/files/4865034/simulation.zip).

I can't help but feel it's not a Docker bug but an EnergyPlus on Linux + Honeybee-Energy generated IDF files.

@chriswmackey I would be super greatful if you could test the zipped folder above by running the `energyplus` command from the `simulation/run/` folder and see what it outputs for you. If you could test it with EnergyPlus 9.3.0 or even better the EnergyPlus binary that was packed with OpenStudio on your machine that would be a great help!

**Comment by chriswmackey** [comment]
@AntoineDao ,
The current honeybee-energy is not compatible with EnergyPlus 9.2 and that error message that you get there is exactly because of this incompatibility. So you would be correct that the particular error you have have there is a "bug" in honeybee-generated IDF files IF you were assuming honeybee was compatible with E+ 9.2 (but, alas, it is not). However, the first error you got was definitely not a "bug" in the honeybee generation process and, given that I have been able to run this exact EnergyPlus simulation [on the Ubuntu Bionic machines of Travis](https://github.com/ladybug-tools/honeybee-energy/blob/master/.travis.yml), it doesn't seem to be some fundamental incompatibility between E+ and Linux.

If it's helpful to your tests, I can give you an IDF that you can run with EnergyPlus 9.2 but I can tell you that it would be a pretty big step backwards for us to downgrade from EnergyPlus 9.3 to EnergyPlus 9.2. Nor do I think that it's really going to solve the problem.

I will try to re-create your error or at least tell you what part of the IDF simulation is causing the SegmentationFault and resulting crash of the image.

**Comment by AntoineDao** [comment]
Thanks for the help. Mind helping me further and pointing specifically to the file with the passing tests you refer to in Travis? Wasn't sure which test was the one that tried to run energy plus on CI.

**Comment by chriswmackey** [comment]
I apologize that I am actually only running the other JSON in the test file through E+ right now (the `model_coliner_verts.json`). But you can see here it being run through E+ on the Travis machine:
https://github.com/ladybug-tools/honeybee-energy/blob/master/tests/run_test.py#L127-L159

I'll add the other ShoeBox.json now just for a sanity check.

**Comment by chriswmackey** [comment]
Ah, you know what, I just realized that you didn't include any simulation parameters in your original command. Can you try passing these sample SimulationParametrs into your command:
https://github.com/ladybug-tools/honeybee-schema/blob/master/samples/simulation_parameter/simulation_par_detailed.json

**Comment by chriswmackey** [comment]
Gosh, I think that was actually the error. I just recreated it on my machine by removing the simulation parameters. I'm really sorry that I missed it (I got way too distracted by the "Segmentation Fault" error). EnergyPlus really should give a much better error in this case.

**Comment by chriswmackey** [comment]
If it is any consolation, I have made the SimulationParameter input required for the queenbee function that runs the simulation. The reason why it's optional in the `simulate` command is that there is usually a .ddy file sitting next to the .epw 99% of the time when people run simulations locally. So the default is to generate some SimulationParameters from that .ddy file if it exists.

I should throw an exception if there's no SimulationParamter and it doesn't find the `.ddy`, though. [You can see that right now that I just let it pass](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/cli/simulate.py#L86-L87) but, now that I know E+ won't give us a useful error message, I should make sure that we catch it on the honeybee side of things before the simulation is run.

**Comment by chriswmackey** [comment]
Ok, I have put in [a much better error message on the honeybee side of things so that hopefully no one ever has to go through this wild goose chase again](https://github.com/ladybug-tools/honeybee-energy/pull/258).

And I think we are ready to merge your PR here, @AntoineDao , unless you want to do any further testing.

**Comment by AntoineDao** [comment]
I'll do a quick test on my end and merge it in afterward. Thanks a lot for the debugging on this one! :smile:

**Comment by AntoineDao** [comment]
@chriswmackey this is ready to go now!

@mostaphaRoudsari I need you to setup the `DOCKER_USERNAME` and `DOCKER_PASSWORD` env vars on Travis for this repo to get the push to Dockerhub to work.

**Comment by chriswmackey** [comment]
Great!. Am I correct in understanding that we should hold off on merging this until @mostaphaRoudsari adds the env vars?

**Comment by mostaphaRoudsari** [comment]
I'm setting this up now. Give me a minute. Travis doesn't show the ladybug tools repos for some reason.

**Comment by chriswmackey** [comment]
I had that issue before @mostaphaRoudsari . I had to sign out and then sign back into Travis.

**Comment by mostaphaRoudsari** [comment]
Done! https://travis-ci.org/github/ladybug-tools/honeybee-energy/settings

**Pull request merged**
